name: Emacs lisp

on:
  push:
    # branches to consider in the event; optional, defaults to all
    branches:
      - master

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - uses: leotaku/elisp-check@master
        with:
          check: melpa
          file: '*.el'
          ignore_warnings: false
          warnings_as_errors: false